[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/public/index.html"
  status = 200
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"